config/routes.rb
Rails.application.routes.draw do
  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  get '/signin' => 'sessions#new'
  post '/signin' => 'sessions#create'
  get '/signout' => 'sessions#destroy'
  
  root to: 'statics#home_page'
  resources :products do
    resources :reviews
  end
end

app/controllers/statics_controller.rb
class StaticsController < ApplicationController
    def home_page
        @most_reviewed_product = Product.product_with_most_reviews
        @made_in_usa = Product.made_in_usa
        @recently_added = Product.recently_added
        render :home_page
    end
end

app/views/statics/home_page.html.erb
<div id="most-reviewed-home">
    <h4>Our most reviewed product!</h4>
    <% if @most_reviewed_product.any? %>
    <ul>
        <% @most_reviewed_product.each do |product| %>
        <li><%= link_to product.name, product_path(product) %></li>
        <% end %>
    </ul>
    <% else %>
    <p>There are no products yet.</p>
    <% end %>
</div>

<div id="most-recent-home">
    <h4>Our three newest products!</h4>
    <% if @recently_added.any? %>
    <ul>
        <% @recently_added.each do |product| %>
        <li><%= link_to product.name, product_path(product) %></li>
        <% end %>
    </ul>
    <% else %>
    <p>There are no products yet.</p>
    <% end %>
</div>

<div id="made-in-usa-home">
    <h4>Locally Produced</h4>
    <% if @made_in_usa.any? %>
    <ul>
        <% @made_in_usa.each do |product| %>
        <li><%= link_to product.name, product_path(product) %></li>
        <% end %>
    </ul>
    <% else %>
    <p>There are no products Made in the USA.</p>
    <% end %>
</div>
<div class="nav-links">
    <p><%= link_to "View all products", products_path %></p>
</div>