config/routes.rb
Rails.application.routes.draw do
  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  get '/signin' => 'sessions#new'
  post '/signin' => 'sessions#create'
  get '/signout' => 'sessions#destroy'
  
  root to: 'statics#home_page'
  resources :products do
    resources :reviews
  end
end

app/models/product.rb
class Product < ApplicationRecord
    scope :product_with_most_reviews, -> {( select("products.id, products.name, count(reviews.id) as reviews_count").joins(:reviews).group("products.id").order("reviews_count DESC").limit(1) )}
    # scope :avg_rating, -> {(  )}
    # SELECT AVG(rating) FROM reviews;
    scope :made_in_usa, -> { where(country_of_origin: "United States of America") }
    scope :recently_added, -> { order(created_at: :desc).limit(3)}
    scope :a_to_z, -> { order("name ASC") }
    scope :z_to_a, -> { order("name DESC") }

    # scope :sum_of_products, -> {( select("") )}
    # scope :search, -> (search_term) { where("name like ?", "%#{search_term}%")}

    has_many :reviews, dependent: :destroy
    validates :name, :cost, :country_of_origin, presence: true

    before_save(:titleize_product)

    private
        def titleize_product
            self.name = self.name.titleize
        end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    before_action :authorize, only: [:index, :new, :show]

    # Code for listing all products
    def index
        @products = Product.all
        if params[:a_to_z]
            @products = Product.a_to_z
        elsif params[:z_to_a]
            @products = Product.z_to_a
        elsif params[:product_with_most_reviews]
            @products = Product.product_with_most_reviews
        elsif params[:made_in_usa]
            @products = Product.made_in_usa
        elsif params[:recently_added]
            @products = Product.recently_added
        end
        render :index
    end
    
    # Code for new product form
    def new
        if current_user.admin != true
            redirect_to '/'
            flash[:notice] = "You do not have permission to do that."
        else
            @product = Product.new
            render :new
        end
    end
    
    # Code for creating a new product
    def create
        @product = Product.new(product_params)
        if @product.save
            flash[:notice] = "#{@product.name} was successfully added!"
            redirect_to products_path
        else
            render :new
        end
    end
    
    # Code for edit product form
    def edit
        if current_user.admin != true
            redirect_to '/'
            flash[:notice] = "You do not have permission to do that."
        else
            @product = Product.find(params[:id])
            render :edit
        end
    end
    
    # Code for showing a single product
    def show
        @product = Product.find(params[:id])
        render :show
    end
    
    # Code for updating a product
    def update
        @product = Product.find(params[:id])
        if @product.update(product_params)
            flash[:notice] = "#{@product.name} was successfully updated!"
            redirect_to products_path
        else
            render :edit
        end
    end
    
    # Code for deleting a product
    def destroy
        if current_user.admin != true
            redirect_to '/'
            flash[:notice] = "You do not have permission to do that."
        else
            @product = Product.find(params[:id])
            @product.destroy
            flash[:notice] = "Product was successfully deleted!"
            redirect_to products_path
        end
    end

    private
    def product_params
      params.require(:product).permit(:name, :cost, :country_of_origin)
    end
    
end

app/views/products/edit.html.erb
<h1>Edit product</h1>

<%= render "layouts/product_form" %>

<div class="nav-links">
    <p><%= link_to "Return to products", products_path %></p>
</div>

app/views/products/index.html.erb
<h1>Products</h1>

<div id="all-products">
  <% if @products.any? %>
    <form>
      <div class="form-group">
        <button class="btn btn-success" type="submit" name="a_to_z">A to Z <i class="fas fa-sort-alpha-down"></i>
        </button>
        <button class="btn btn-primary" type="submit" name="z_to_a">Z to A <i class="fas fa-sort-alpha-down-alt"></i></button>
        <div class="dropdown">
          <button class="btn btn-info dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Sort <i class="fas fa-filter"></i>
          </button>
          <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <button class="btn btn-primary" type="submit" name="made_in_usa">Made In USA</button>
            <br>
            <br>
            <button class="btn btn-secondary" type="submit" name="recently_added">Most Recent</button>
            <br>
            <br>
            <button class="btn btn-success" type="submit" name="product_with_most_reviews">Most Reviewed Product</button>
          </div>
        </div>
      </div>
    </form>
    <ul class="product-listing">
      <% @products.each do |product| %>
        <div class="product-view">
          <li><h5><%= link_to product.name, product_path(product, class:"products-titles") %></h5></li>
          <%= link_to image_tag("https://i.picsum.photos/id/39/3456/2304.jpg"), product_path(product), class: "placeholder-image" %>
          <p class="product-description">Lorem ipsum product descripsum a deo inimum malac a marum ilum unde omnis iste natus error sit voluptatem accusantium doloremque laudantium...</p>
          <p class="product-view-link"><%= link_to "View Details", product_path(product) %></p>
        </div>
      <% end %>
    </ul>
  <% else %>
    <p>There are no products yet.</p>
  <% end %>
</div>

<div class="nav-links">
  <p><%= link_to "Create new product", new_product_path %></p>
  <p><%= link_to "View all products", products_path %></p>
</div>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render "layouts/product_form" %>
<div class="nav-links">
    <p><%= link_to "Return to products", products_path %></p>
</div>

app/views/products/show.html.erb
<h1>Product: <%= @product.name %></h1>
<p><img src="https://i.picsum.photos/id/39/3456/2304.jpg" class="placeholder-image"></p>
<h3>Cost: $<%= @product.cost %></h3>
<h3>Country: <%= @product.country_of_origin %></h3>
<hr>

<div id="individual-product-reviews">
  <% if @product.reviews.any? %>
    <h4>Here are the reviews for this product by author:</h4>

    <% @product.reviews.each do |review| %>
      <ul>
        <li>
          <%= link_to review.author, product_review_path(@product, review) %>
        </li>
      </ul>
    <% end %>
  <% else %>
    <p>No reviews are listed for this product.</p>
  <% end %>
</div>

<div class="nav-links">
  <p><%= link_to "Add a review", new_product_review_path(@product) %></p>
    
  <p><%= link_to "Edit", edit_product_path(@product) %></p>
  <p><%= link_to "Delete product", product_path(@product),
                            :data => {:confirm => "Are you sure?",
                                          :method => "delete"} %></p>
    
  <p><%= link_to "Return to products", products_path %></p>
</div>

