config/routes.rb
Rails.application.routes.draw do
  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  get '/signin' => 'sessions#new'
  post '/signin' => 'sessions#create'
  get '/signout' => 'sessions#destroy'
  
  root to: 'statics#home_page'
  resources :products do
    resources :reviews
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    before_action :authorize, only: [:new, :edit, :update, :destroy]

    def new
        @product = Product.find(params[:product_id])
        @review = @product.reviews.new 
    end
    
    def create
        @product = Product.find(params[:product_id])
        @review = @product.reviews.new(review_params)
        if @review.save
            flash[:notice] = "#{@product.name} has been reviewed!"
            redirect_to product_path(@product)
        else
            flash[:alert] = "Something went wrong."
            render :new
        end
    end
    
    def show
        @product = Product.find(params[:product_id])
        @review = Review.find(params[:id])
        render :show        
    end
    
    def edit
        if current_user.admin != true
            redirect_to '/'
            flash[:notice] = "You do not have permission to do that."
        else
            @product = Product.find(params[:product_id])
            @review = Review.find(params[:id])
            render :edit
        end
    end
    
    def update
        @review = Review.find(params[:id])
        if @review.update(review_params)
            flash[:notice] = "#{@review.author}'s review has been updated!"
            redirect_to product_path(@review.product)
        else
            flash[:alert] = "Something went wrong."
            redirect_to product_path(@review.product)
        end
    end

    def destroy
        if current_user.admin != true
            redirect_to '/'
            flash[:notice] = "You do not have permission to do that."
        else
            @review = Review.find(params[:id])
            @review.destroy
            flash[:notice] = "Review successfully removed."
            redirect_to product_path(@review.product)
        end
    end
    
    private
        def review_params
            params.require(:review).permit(:author, :content_body, :rating)
        end
end

app/views/reviews/edit.html.erb
<h2> <%= @product.name %></h2>
<h3>Edit <%= @review.author %>'s review:</h3>

<%= render "layouts/review_form" %>

app/views/reviews/new.html.erb
<h2> <%= @product.name %></h2>
<h1>Add a new review:</h1>

<%= render "layouts/review_form" %>

app/views/reviews/show.html.erb
<h1>Product: <%= @product.name %> </h1>
<h2>Review by: <%= @review.author %> </h2>
<% if @review.rating %>
    <% x = 0 %>
    <% stars = [] %>
    <% until (x >= @review.rating) %>
    <% x += 1 %>
    <% stars.push('⭐️') %>
    <% end %>
    <p><%= stars.join(" ") %></p>
    <% else %>
    <p><%= "#{@product.name}" %> has not been rated yet.</p>
<% end %>
<h4 class="product-review-text"><%= @review.content_body %> </h4>
<div class="nav-links">
    <p><%= link_to "Edit review", edit_product_review_path(@product, @review) %></p>
    <p><%= link_to "Delete review", product_review_path(@product, @review),
                            :data => {:confirm => "Are you sure?",
                                        :method => "delete"} %></p>

    <p><%= link_to "Return to product", product_path(@product) %></p>
</div>